### PR TITLE
Mschaara/merge master

### PR DESCRIPTION
**Pull request by mchaarawi**

### CODE REVIEW

**Comment by mchaarawi** [comment]
@brianjmurrell 
this is still failing leap build.. it's been like that for ~2 weeks now.
the daos branch is a little outdated im afraid now.

**Comment by brianjmurrell** [comment]
> @brianjmurrell
> this is still failing leap build.. it's been like that for ~2 weeks now.
> the daos branch is a little outdated im afraid now.

Leap build was [fixed 5 days ago](https://github.com/daos-stack/ior-hpc/commit/712b4f3313ec8c40e8bc9b11c6165082075c4cd0).  [daos branch build #58](https://build.hpdd.intel.com/job/daos-stack/job/ior-hpc/job/daos/58/) of it was completely successful.

Have you merged it to this PR yet?

**Comment by mchaarawi** [comment]
hmm no, let me do that

**Comment by mchaarawi** [comment]
that seems to do it. thanks!

**Pull request merged**
